# Generated by Django 2.1.2 on 2018-10-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20181001_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='sobrenome',
            field=models.CharField(default='Sena', max_length=100, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
    ]
