# Generated by Django 2.1.2 on 2018-10-19 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_cadastro_sobrenome'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemDeCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_code', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'ordem de compra',
                'verbose_name_plural': 'ordems de compra',
                'ordering': ('cli_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ('nome',), 'verbose_name': 'cadastro', 'verbose_name_plural': 'cadastros'},
        ),
        migrations.AddField(
            model_name='ordemdecompra',
            name='cli_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Cadastro', verbose_name='bairro'),
        ),
    ]
