# Generated by Django 2.1.2 on 2019-01-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_auto_20190117_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='cidade_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.Cidade'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='estado_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.Estado'),
        ),
    ]
